Aim29:
  Boxicons:
    Icon:
      styles: # enable or disable styles
        regular: true
        solid: true
        logos: true

Neos:
  Neos:
    fusion:
      autoInclude:
        Aim29.Boxicons.Icon: true
    userInterface:
      translation:
        autoInclude:
          Aim29.Boxicons.Icon:
            - 'NodeTypes/*'
